# Generated by Django 5.1.5 on 2025-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
